theme: just-the-docs
title: Flintlock District Homepage
description: Bookmark this to keep an eye on my project updates!
url: https://just-the-docs.github.io

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template
